name: next-blog-github-actions

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  token-transformer:
    runs-on: ubuntu-latest
    steps:
      - name: token-toransformer
        run: |
          ./node_modules/.bin/token-transformer tokens.json output.json
          style-dictionary build --config style-dictionary.config.json